#!/usr/bin/env python3
"""Generate notices from locked, cached crates and reviewed upstream supplements."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "THIRD_PARTY_NOTICES.md"


def digest(data):
    return hashlib.sha256(data).hexdigest()


def generate():
    metadata = json.loads(subprocess.check_output(
        ["cargo", "metadata", "--locked", "--offline", "--format-version", "1"], cwd=ROOT))
    extra = json.loads((ROOT / "licenses/upstream.json").read_text())
    texts = {}
    entries = []
    packages = sorted((p for p in metadata["packages"] if p["source"]),
                      key=lambda p: (p["name"], p["version"]))
    for package in packages:
        if not package["source"].startswith("registry+"):
            raise ValueError("Non-registry dependency requires source provenance review")
        key = package["name"] + "@" + package["version"]
        root = Path(package["manifest_path"]).parent
        source = f'https://crates.io/api/v1/crates/{package["name"]}/{package["version"]}/download'
        items = []
        for path in sorted(root.rglob("*")):
            if not path.is_file():
                continue
            name = path.name.lower()
            relative = path.relative_to(root).as_posix()
            is_license = name.startswith(("license", "licence", "copying", "notice", "copyright"))
            is_font_notice = package["name"] == "epaint_default_fonts" and relative.startswith("fonts/") and name.endswith(".txt")
            is_authors = name in ("authors", "authors.txt", "authors.md")
            if is_license or is_font_notice or is_authors or relative == package.get("license_file"):
                items.append((relative, source, path.read_text(encoding="utf-8")))
        # Preserve file-level copyright statements as well as top-level license notices.
        statements = set()
        for path in sorted(root.rglob("*.rs")):
            for line in path.read_text(encoding="utf-8").splitlines():
                if re.match(r"\s*(?://[!/]*|\*)\s*(?:SPDX-FileCopyrightText:|Copyright\s+(?:\(c\)|\(C\)|[0-9]))", line):
                    statements.add(line.strip())
        if statements:
            items.append(("Copyright statements from Rust source files", source, "\n".join(sorted(statements)) + "\n"))
        for entry in extra["packages"].get(key, []):
            body = extra["texts"][entry["sha256"]]
            if digest(body.encode()) != entry["sha256"]:
                raise ValueError(f"Supplement checksum mismatch: {key}")
            items.append((entry["path"], entry["url"], body))
        if not items or not package["license"]:
            raise ValueError(f"Missing license evidence: {key}")
        entries.extend([f'### {package["name"]} {package["version"]}', "",
                        f'Declared license: `{package["license"]}`', "",
                        f"Source archive: <{source}>", ""])
        if package["authors"]:
            entries.extend(["Upstream package authors: " + "; ".join(package["authors"]), ""])
        for name, origin, body in items:
            sha = digest(body.encode())
            texts[sha] = body
            entries.append(f"- {name}: [text {sha[:16]}](#text-{sha[:16]}); origin: <{origin}>")
        entries.append("")
    lock_hash = digest((ROOT / "Cargo.lock").read_bytes())
    header = f"""# Third-party notices for rustVN

Generated by `python3 scripts/generate_licenses.py`. Do not edit manually.
Cargo.lock SHA-256: `{lock_hash}`

This inventory covers {len(packages)} registry packages, including optional,
build, development and other-platform dependencies. It is a conservative
superset, not a list of components linked into every executable.
Upstream notices are preserved; alternative license texts do not mean that
all alternatives are selected. Where offered, rustVN uses the MIT option
(in particular for r-efi); additional AND terms remain applicable.
Third-party components retain their own licenses, independent of rustVN's MIT license.

Ship this entire file and LICENSE with executable distributions.
See [distribution guidance](docs/licensing.md) for native libraries and fonts.

## MPL-2.0 source availability

option-ext 0.2.0 is used without modification under MPL-2.0.
Its corresponding source, including its MPL license, is available at:
<https://crates.io/api/v1/crates/option-ext/0.2.0/download>
Readers may obtain and modify that source under MPL-2.0.
The full MPL text is included below in the option-ext entry's linked license text.

## Embedded fonts

The epaint_default_fonts entry includes Hack (MIT and Bitstream Vera notices),
Noto Emoji (SIL OFL 1.1), Ubuntu Light (Ubuntu Font Licence 1.0), and
emoji-icon-font (MIT). Their original notices are reproduced below.
Japanese fonts loaded from the user's OS or RUSTVN_FONT are not bundled.

## Packages

"""
    # Fail explicitly if the manually explained MPL version changes.
    if not any(p["name"] == "option-ext" and p["version"] == "0.2.0" for p in packages):
        raise ValueError("Review MPL source availability instructions after dependency changes")
    out = header + "\n".join(entries) + "\n## License and notice texts\n\n"
    for sha, body in sorted(texts.items()):
        out += f'<a id="text-{sha[:16]}"></a>\n\n### Text {sha[:16]}\n\n'
        fence = "`" * max(8, max((len(s) for s in re.findall(r"`+", body)), default=0) + 1)
        out += fence + "text\n" + body + ("" if body.endswith("\n") else "\n") + fence + "\n\n"
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != result:
            sys.exit("Third-party notices are stale; regenerate and review them.")
        print("Third-party notices match Cargo.lock and reviewed source texts.")
    else:
        OUTPUT.write_text(result)
        print("Generated THIRD_PARTY_NOTICES.md; review before updating privacy exceptions.")


if __name__ == "__main__":
    main()
